### ISSUE TITLE
ปรับ/เพิ่ม Form-wizard 

### ISSUE THREAD

**Issue by firdows** [andatech-hrm/yii2-person#2]
- เพิ่ม step 5 การศึกษา
- เพิ่ม step 6 การบรรจุครั้งแรก ตำแหน่ง พร้อมเงินเดือน และวันเริ่มงาน-วันสิ้นสุด(วันเกษียณ)
- เพิ่ม step 7 กำหนดวันลา

ปรับให้กรอกทีเดียวให้หมดใน form-wizard

**Comment by kuakling** [comment]
**New step**

1. รวม basic + detail + รูปแรก
2. Education
3. Parent + Child
4. Position + Edoc
5. Leave Permission + ผู้เกี่ยวข้อง
6. User Account

Save

**Comment by firdows** [comment]
เรียบร้อย
